# Copy this to a file config.yml (which is gitignored) and enter your secrets
storage:
  connection-string: "CONNECTION_STRING"
  container: "INSIGHTS_CONTAINER_NAME"

search:
  service-name: "SEARCH_SERVICE_NAME"
  api-version: "2020-06-30"
  api-key: "API_KEY"
  index-name:  "INDEX_NAME"
  index-schema-path: "client/index-schema.json"

files:
  vi-output-directory: "client/files/vi-files"
  processed-directory: "client/files/processed"
  ingested-file: "ingested.txt"
  failed-to-ingest-file: "failed-to-ingest.txt"

parser:
  milliseconds-interval: 10000
